// components/tabs/index.vue
<template>
  <div class="friendship-tabs">
    <ad-button
      v-for="tab in tabs"
      :key="tab"
      :label="toTitleCase(tab)"
      :text="activeTab !== tab"
      ad-type="main"
      class="tab-button"
      @click="$emit('update:activeTab', tab)"
    />
  </div>
</template>

<script setup lang="ts">
import type { NucFriendshipTabType } from 'nucleify'

defineProps<{
  activeTab: NucFriendshipTabType
}>()

defineEmits<{
  'update:activeTab': [value: NucFriendshipTabType]
}>()

const tabs: NucFriendshipTabType[] = ['friends', 'requests', 'blocked']

function toTitleCase(str: string): string {
  return str.charAt(0).toUpperCase() + str.slice(1)
}
</script>

<style lang="scss" scoped>
@import 'index';
</style>

// components/tabs/index.tsx
'use client'

import React from 'react'

import type { NucFriendshipTabType } from 'nucleify'
import { AdButton } from 'nucleify'

import './_index.scss'

interface NucFriendshipTabsProps {
  activeTab: NucFriendshipTabType
  onTabChange: (tab: NucFriendshipTabType) => void
}

export const NucFriendshipTabs: React.FC<NucFriendshipTabsProps> = ({
  activeTab,
  onTabChange,
}) => {
  const tabs: NucFriendshipTabType[] = ['friends', 'requests', 'blocked']

  function toTitleCase(str: string): string {
    return str.charAt(0).toUpperCase() + str.slice(1)
  }

  return (
    <div className="friendship-tabs">
      {tabs.map((tab) => (
        <AdButton
          key={tab}
          label={toTitleCase(tab)}
          text={activeTab !== tab}
          adType="main"
          className="tab-button"
          onClick={() => onTabChange(tab)}
        />
      ))}
    </div>
  )
}
