// index.tsx
'use client'

import React, { useEffect } from 'react'

import {
  AdPopover,
  friendshipRequests,
  isMobile,
  NucFriendshipPopover,
  PositionType,
} from 'nucleify'

import './_index.scss'

interface NucFriendshipProps {
  position: PositionType
}

export const NucFriendship: React.FC<NucFriendshipProps> = ({ position }) => {
  const { loading, getAllFriendships } = friendshipRequests('next')

  useEffect(() => {
    getAllFriendships(true)
  }, [])

  if (loading) return null

  return (
    <AdPopover
      dismissable
      icon="prime:users"
      position={position}
      popoverClass="friendship-popover"
      buttonText={isMobile() ? '' : 'Friends'}
      buttonClass="friendship-popover-toggle"
    >
      <NucFriendshipPopover />
    </AdPopover>
  )
}

// index.vue
<template>
  <ad-popover
    v-if="!loading"
    dismissable
    icon="prime:users"
    :position="position"
    popover-class="friendship-popover"
    :button-text="isMobile() ? '' : 'Friends'"
    button-class="friendship-popover-toggle"
  >
    <nuc-friendship-popover />
  </ad-popover>
</template>

<script setup lang="ts">
import { friendshipRequests } from 'nucleify'

defineProps<{
  position: PositionType
}>()

const { loading, getAllFriendships } = friendshipRequests()

onMounted(() => {
  getAllFriendships(true)
})
</script>

<style lang="scss">
@import '.';
</style>
