// components/friends-list/index.tsx
'use client'

import React from 'react'

import {
  AdButton,
  AdParagraph,
  NucFriendItem,
  type NucFriendshipObjectInterface,
} from 'nucleify'

import './_index.scss'

interface NucFriendshipFriendsListProps {
  friends: NucFriendshipObjectInterface[]
  onBlock: (friendId: number) => void
  onRemove: (friendId: number) => void
}

export const NucFriendshipFriendsList: React.FC<
  NucFriendshipFriendsListProps
> = ({ friends, onBlock, onRemove }) => {
  return (
    <div className="friends-list">
      {friends.length === 0 && (
        <div className="empty-state">
          <AdParagraph text="No friends found" />
        </div>
      )}
      {friends.map((friendship) => (
        <NucFriendItem
          key={friendship.id}
          friendship={friendship}
          actions={({ friendId }) => (
            <>
              <AdButton
                icon="prime:ban"
                text
                rounded
                nuiType="main"
                onClick={() => onBlock(friendId)}
              />
              <AdButton
                icon="prime:trash"
                text
                rounded
                severity="danger"
                onClick={() => onRemove(friendId)}
              />
            </>
          )}
        />
      ))}
    </div>
  )
}

// components/friends-list/index.vue
<template>
  <div class="friends-list">
    <div v-if="friends.length === 0" class="empty-state">
      <ad-paragraph text="No friends found" />
    </div>
    <nuc-friend-item
      v-for="friendship in friends"
      :key="friendship.id"
      :friendship="friendship"
    >
      <template #actions="{ friendId }">
        <ad-button
          icon="prime:ban"
          text
          rounded
          ad-type="main"
          @click="$emit('block', friendId)"
        />
        <ad-button
          icon="prime:trash"
          text
          rounded
          severity="danger"
          @click="$emit('remove', friendId)"
        />
      </template>
    </nuc-friend-item>
  </div>
</template>

<script setup lang="ts">
import type { NucFriendshipObjectInterface } from 'nucleify'

defineProps<{
  friends: NucFriendshipObjectInterface[]
}>()

defineEmits<{
  block: [friendId: number]
  remove: [friendId: number]
}>()
</script>

<style lang="scss" scoped>
@import 'index';
</style>
