// components/requests-list/index.tsx
'use client'

import React from 'react'

import {
  AdButton,
  AdParagraph,
  NucFriendItem,
  type NucFriendshipObjectInterface,
} from 'nucleify'

import './_index.scss'

interface NucFriendshipRequestsListProps {
  requests: NucFriendshipObjectInterface[]
  onAccept: (senderId: number) => void
  onDeny: (senderId: number) => void
}

export const NucFriendshipRequestsList: React.FC<
  NucFriendshipRequestsListProps
> = ({ requests, onAccept, onDeny }) => {
  return (
    <div className="requests-list">
      {requests.length === 0 && (
        <div className="empty-state">
          <AdParagraph text="No requests found" />
        </div>
      )}
      {requests.map((friendship) => (
        <NucFriendItem
          key={friendship.id}
          friendship={friendship}
          actions={({ friendId }) => (
            <>
              <AdButton
                icon="prime:check"
                text
                rounded
                nuiType="main"
                onClick={() => onAccept(friendId)}
              />
              <AdButton
                icon="prime:times"
                text
                rounded
                severity="danger"
                onClick={() => onDeny(friendId)}
              />
            </>
          )}
        />
      ))}
    </div>
  )
}

// components/requests-list/index.vue
<template>
  <div class="requests-list">
    <div v-if="requests.length === 0" class="empty-state">
      <ad-paragraph text="No requests found" />
    </div>
    <nuc-friend-item
      v-for="friendship in requests"
      :key="friendship.id"
      :friendship="friendship"
    >
      <template #actions="{ friendId }">
        <ad-button
          icon="prime:check"
          text
          rounded
          ad-type="main"
          @click="$emit('accept', friendId)"
        />
        <ad-button
          icon="prime:times"
          text
          rounded
          severity="danger"
          @click="$emit('deny', friendId)"
        />
      </template>
    </nuc-friend-item>
  </div>
</template>

<script setup lang="ts">
import type { NucFriendshipObjectInterface } from 'nucleify'

defineProps<{
  requests: NucFriendshipObjectInterface[]
}>()

defineEmits<{
  accept: [senderId: number]
  deny: [senderId: number]
}>()
</script>

<style lang="scss" scoped>
@import 'index';
</style>
