// components/add-friend/index.vue
<template>
  <div class="add-friend">
    <div class="add-friend-input">
      <ad-input-text
        v-model="searchEmail"
        placeholder="User email"
        ad-type="main"
        class="search-input"
        @keyup.enter="handleAddFriend"
      />
      <ad-button
        label="Invite"
        icon="prime:user-plus"
        ad-type="main"
        :loading="loading"
        @click="handleAddFriend"
      />
    </div>
  </div>
</template>

<script setup lang="ts">
import { friendshipRequests, userRequests } from 'nucleify'

import { useAddFriend } from './utils'

const friendship = friendshipRequests()
const users = userRequests()

const searchEmail = ref('')
const loading = computed(() => friendship.loading.value)

const { handleAddFriend: handleAddFriendFn } = useAddFriend({
  searchEmail,
  friendship,
  users,
})

async function handleAddFriend() {
  await handleAddFriendFn()
  searchEmail.value = ''
}
</script>

<style lang="scss" scoped>
@import 'index';
</style>

// components/add-friend/index.tsx
'use client'

import React, { useState } from 'react'

import {
  AdButton,
  AdInputText,
  friendshipRequests,
  useAddFriend,
  userRequests,
} from 'nucleify'

import './_index.scss'

export const NucFriendshipAddFriend: React.FC = () => {
  const friendship = friendshipRequests('next')
  const users = userRequests(undefined, 'next')

  const [searchEmail, setSearchEmail] = useState('')

  const { handleAddFriend: handleAddFriendFn } = useAddFriend({
    searchEmail,
    friendship,
    users,
  })

  async function handleAddFriend() {
    await handleAddFriendFn()
    setSearchEmail('')
  }

  return (
    <div className="add-friend">
      <div className="add-friend-input">
        <AdInputText
          value={searchEmail}
          onChange={(e) => setSearchEmail(e.target.value)}
          placeholder="User email"
          adType="main"
          className="search-input"
          onKeyUp={(e) => e.key === 'Enter' && handleAddFriend()}
        />
        <AdButton
          label="Invite"
          icon="prime:user-plus"
          adType="main"
          className="invite-button"
          loading={friendship.loading}
          onClick={handleAddFriend}
        />
      </div>
    </div>
  )
}
