// components/blocked-list/index.vue
<template>
  <div class="blocked-list">
    <div v-if="blocked.length === 0" class="empty-state">
      <ad-paragraph text="No blocked users" />
    </div>
    <nuc-friend-item
      v-for="friendship in blocked"
      :key="friendship.id"
      :friendship="friendship"
    >
      <template #actions="{ friendId }">
        <ad-button
          icon="prime:unlock"
          text
          rounded
          ad-type="main"
          @click="$emit('unblock', friendId)"
        />
      </template>
    </nuc-friend-item>
  </div>
</template>

<script setup lang="ts">
import type { NucFriendshipObjectInterface } from 'nucleify'

defineProps<{
  blocked: NucFriendshipObjectInterface[]
}>()

defineEmits<{
  unblock: [friendId: number | string]
}>()
</script>

<style lang="scss">
@import 'index';
</style>

// components/blocked-list/index.tsx
'use client'

import React from 'react'

import {
  AdButton,
  AdParagraph,
  NucFriendItem,
  type NucFriendshipObjectInterface,
} from 'nucleify'

import './_index.scss'

interface NucFriendshipBlockedListProps {
  blocked: NucFriendshipObjectInterface[]
  onUnblock: (friendId: number) => void
}

export const NucFriendshipBlockedList: React.FC<
  NucFriendshipBlockedListProps
> = ({ blocked, onUnblock }) => {
  return (
    <div className="blocked-list">
      {blocked.length === 0 && (
        <div className="empty-state">
          <AdParagraph text="No blocked users" />
        </div>
      )}
      {blocked.map((friendship) => (
        <NucFriendItem
          key={friendship.id}
          friendship={friendship}
          actions={({ friendId }) => (
            <AdButton
              icon="prime:unlock"
              text
              rounded
              nuiType="main"
              onClick={() => onUnblock(friendId)}
            />
          )}
        />
      ))}
    </div>
  )
}
