// components/popover/index.vue
<template>
  <div class="friendship-popover-container">
    <ad-heading :tag="3" text="Friends" class="friendship-header" />

    <div class="friendship-content">
      <nuc-friendship-add-friend />

      <nuc-friendship-tabs
        :active-tab="activeTab"
        @update:active-tab="activeTab = $event"
      />

      <nuc-friendship-friends-list
        v-if="activeTab === 'friends'"
        :friends="friends"
        @block="handleBlockFriend"
        @remove="handleRemoveFriend"
      />

      <nuc-friendship-requests-list
        v-if="activeTab === 'requests'"
        :requests="requests"
        @accept="handleAcceptRequest"
        @deny="handleDenyRequest"
      />

      <nuc-friendship-blocked-list
        v-if="activeTab === 'blocked'"
        :blocked="blocked"
        @unblock="handleUnblockFriend"
      />
    </div>
  </div>
</template>

<script setup lang="ts">
import { friendshipRequests } from 'nucleify'

import { useFriendshipPopover } from './utils'

const {
  results,
  acceptRequest,
  denyRequest,
  removeFriend,
  blockFriend,
  unblockFriend,
  getAllFriendships,
} = friendshipRequests()

const {
  activeTab,
  friends,
  requests,
  blocked,
  handleAcceptRequest,
  handleDenyRequest,
  handleRemoveFriend,
  handleBlockFriend,
  handleUnblockFriend,
} = useFriendshipPopover({
  results,
  acceptRequest,
  denyRequest,
  removeFriend,
  blockFriend,
  unblockFriend,
})

onMounted(() => {
  getAllFriendships()
})
</script>

<style lang="scss">
@import 'index';
</style>

// components/popover/index.tsx
'use client'

import React, { useEffect } from 'react'

import {
  AdHeading,
  friendshipRequests,
  NucFriendshipAddFriend,
  NucFriendshipBlockedList,
  NucFriendshipFriendsList,
  NucFriendshipRequestsList,
  NucFriendshipTabs,
  useFriendshipPopover,
} from 'nucleify'

import './_index.scss'

export const NucFriendshipPopover: React.FC = () => {
  const {
    results,
    acceptRequest,
    denyRequest,
    removeFriend,
    blockFriend,
    unblockFriend,
    getAllFriendships,
  } = friendshipRequests('next')

  const {
    activeTab,
    setActiveTab,
    friends,
    requests,
    blocked,
    handleAcceptRequest,
    handleDenyRequest,
    handleRemoveFriend,
    handleBlockFriend,
    handleUnblockFriend,
  } = useFriendshipPopover({
    results: results || [],
    acceptRequest,
    denyRequest,
    removeFriend,
    blockFriend,
    unblockFriend,
  })

  useEffect(() => {
    getAllFriendships()
  }, [])

  return (
    <div className="friendship-popover-container">
      <div className="friendship-header">
        <AdHeading tag={3} text="Friends" />
      </div>

      <div className="friendship-content">
        <NucFriendshipAddFriend />

        <NucFriendshipTabs activeTab={activeTab} onTabChange={setActiveTab} />

        {activeTab === 'friends' && (
          <NucFriendshipFriendsList
            friends={friends}
            onBlock={handleBlockFriend}
            onRemove={handleRemoveFriend}
          />
        )}

        {activeTab === 'requests' && (
          <NucFriendshipRequestsList
            requests={requests}
            onAccept={handleAcceptRequest}
            onDeny={handleDenyRequest}
          />
        )}

        {activeTab === 'blocked' && (
          <NucFriendshipBlockedList
            blocked={blocked}
            onUnblock={handleUnblockFriend}
          />
        )}
      </div>
    </div>
  )
}
