// components/friend-item/index.vue
<template>
  <div class="friend-item">
    <div class="friend-info">
      <ad-icon icon="prime:user" size="1.5em" />
      <div class="friend-details">
        <ad-paragraph :text="friendship.friend.name" />
        <ad-paragraph :text="friendship.friend.email" class="friend-email" />
      </div>
    </div>
    <div class="friend-actions">
      <slot name="actions" :friend-id="friendship.friend.id" />
    </div>
  </div>
</template>

<script setup lang="ts">
import type { NucFriendshipObjectInterface } from 'nucleify'

defineProps<{
  friendship: NucFriendshipObjectInterface
}>()
</script>

<style lang="scss">
@import 'index';
</style>

// components/friend-item/index.tsx
'use client'

import React from 'react'

import {
  AdIcon,
  AdParagraph,
  type NucFriendshipObjectInterface,
} from 'nucleify'

import './_index.scss'

interface NucFriendItemProps {
  friendship: NucFriendshipObjectInterface
  actions?: (props: { friendId: number }) => React.ReactNode
}

export const NucFriendItem: React.FC<NucFriendItemProps> = ({
  friendship,
  actions,
}) => {
  return (
    <div className="friend-item">
      <div className="friend-info">
        <AdIcon icon="prime:user" size="1.5em" />
        <div className="friend-details">
          <AdParagraph text={friendship.friend.name} />
          <div className="friend-email">
            <AdParagraph text={friendship.friend.email} />
          </div>
        </div>
      </div>
      <div className="friend-actions">
        {actions?.({ friendId: friendship.friend.id })}
      </div>
    </div>
  )
}
